import glob
import os.path
import sys

# import variables from other scons files
Import( '*' )
env = masterEnv.Clone()

if sys.platform.startswith("linux") and have_utvision:

	env.AppendUnique( **mergeOptions( utdataflow_all_options, utvision_all_options ) )

	# take driver name from directory name, replace if you don't like the result
	driverName = "Video4LinuxFramegrabber"

	# automatically glob files
	headers = globSourceFiles( '*.h' )
	sources = globSourceFiles( '*.cpp' ) 

	# compile driver
	setupSingleComponentBuild(env, sources, driverName, 'v4l')
	
	
